Repository SWM-snowWhite/SeekTam, pull requests merged in 2023-11, with the labels that each got.

#196 feat: Elasticsearch를 적용해 상품 검색 API 성능 개선
  backend/build.gradle
  backend/src/main/java/food/backend/search/config/ElasticsearchConfig.java
  backend/src/main/java/food/backend/search/controller/FoodController.java
  backend/src/main/java/food/backend/search/controller/ProductSearchController.java
  backend/src/main/java/food/backend/search/dao/ProductDao.java
  backend/src/main/java/food/backend/search/dao/ProductDetailDao.java
  backend/src/main/java/food/backend/search/dao/ProductKeywordDao.java
  backend/src/main/java/food/backend/search/dto/ProductDetailDto.java
  backend/src/main/java/food/backend/search/dto/ProductDto.java
  backend/src/main/java/food/backend/search/model/KeywordAndNutrientEs.java
  backend/src/main/java/food/backend/search/service/ProductSearchService.java
Labels: ✨ Feature, 🔨Refactoring, 🖥️ Server, 📚 Story, ⏳ TODO

#197 refactor: 엘라스틱서치를 이용한 검색 API 코드 개선
  backend/src/main/java/food/backend/search/dao/ProductDao.java
  backend/src/main/java/food/backend/search/dao/ProductKeywordDao.java
Labels: 🔨Refactoring, 🖥️ Server, ⏳ TODO

#198 fix: ProductKeywordDao NPE 문제 해결
  backend/src/main/java/food/backend/oauth/common/filter/AuthenticationFilter.java
  backend/src/main/java/food/backend/search/dao/ProductKeywordDao.java
Labels: 🐞 Bug Fix, 🖥️ Server

#201 design: 메인화면 및 식품 상세정보 CSS 수정
  backend/src/main/java/food/backend/oauth/common/filter/AuthenticationFilter.java
  backend/src/main/java/food/backend/oauth/common/jwt/JwtProvider.java
  backend/src/main/java/food/backend/oauth/common/jwt/JwtProviderImpl.java
  backend/src/main/java/food/backend/search/config/ElasticsearchConfig.java
  backend/src/main/java/food/backend/search/controller/ProductSearchController.java
  backend/src/main/java/food/backend/search/dao/ProductDao.java
  backend/src/main/java/food/backend/search/dao/ProductDetailDao.java
  backend/src/main/java/food/backend/search/dao/ProductKeywordDao.java
  backend/src/main/java/food/backend/search/service/ProductSearchService.java
  client/src/App.tsx
  client/src/components/ComparisonFood.tsx
  client/src/components/Food.tsx
  client/src/components/FoodInfoComponent.tsx
  client/src/components/FoodList.tsx
  client/src/components/Footer.tsx
  client/src/components/KeywordSearchBar.tsx
  client/src/components/KeywordSearchPageBar.tsx
  client/src/components/MallRanking.tsx
  client/src/components/Navigator.tsx
  client/src/components/NotFound.tsx
  client/src/components/SearchOption.tsx
  client/src/components/ViewsRanking.tsx
  client/src/components/modal/ComparisonViewModal.tsx
  client/src/components/modal/InfoModal.tsx
  client/src/index.tsx
  client/src/pages/CustomerSupport.tsx
  client/src/pages/FoodDetail.tsx
  client/src/pages/FoodsDetail.tsx
  client/src/pages/Main.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Search.tsx
  client/src/pages/Signup.tsx
  client/src/pages/WishList.tsx
Labels: 🐞 Bug Fix, 📱 Client, 🌎 Deploy, 🔨Refactoring, 🖥️ Server, ⏳ TODO

#207 design: 페이지별 CSS 디자인 수정
  backend/docs/deprecated-list.html
  backend/docs/food/backend/search/controller/FoodController.html
  backend/src/main/java/food/backend/member/controller/MemberController.java
  backend/src/main/java/food/backend/member/dao/LikeDao.java
  backend/src/main/java/food/backend/member/service/MemberService.java
  backend/src/main/java/food/backend/member/service/MemberServiceImpl.java
  backend/src/main/java/food/backend/search/controller/FoodController.java
  backend/src/main/java/food/backend/search/dao/FoodKeywordDao.java
  backend/src/main/java/food/backend/search/dao/FoodListDao.java
  backend/src/main/java/food/backend/search/dao/ProductDetailDao.java
  backend/src/main/java/food/backend/search/dto/FoodRankingResponseDto.java
  backend/src/main/java/food/backend/search/service/ProductSearchService.java
  backend/src/test/java/food/backend/FoodSearchServiceTest.java
  backend/src/test/java/food/backend/mall/FoodKeywordRankingDaoTest.java
  backend/src/test/java/food/backend/mall/RedisRepositoryTest.java
  client/src/App.tsx
  client/src/components/AgreementUtilization.tsx
  client/src/components/ComparisonFood.tsx
  client/src/components/Food.tsx
  client/src/components/FoodInfoComponent.tsx
  client/src/components/FoodList.tsx
  client/src/components/Footer.tsx
  client/src/components/FooterMain.tsx
  client/src/components/KeywordComponent.tsx
  client/src/components/KeywordSearchBar.tsx
  client/src/components/KeywordSearchPageBar.tsx
  client/src/components/MallRanking.tsx
  client/src/components/Navigator.tsx
  client/src/components/NavigatorExceptSearch.tsx
  client/src/components/NotFound.tsx
  client/src/components/PrivacyPolicy.tsx
  client/src/components/Range.tsx
  client/src/components/SearchMiniOptionComp.tsx
  client/src/components/SearchOption.tsx
  client/src/components/SearchOptionBar.tsx
  client/src/components/ViewsRanking.tsx
  client/src/components/WishListItem.tsx
  client/src/components/modal/ComparisonModal.tsx
  client/src/components/modal/ComparisonViewModal.tsx
  client/src/index.tsx
  client/src/pages/BackgroundLeft.tsx
  client/src/pages/BackgroundRight.tsx
  client/src/pages/CustomerSupport.tsx
  client/src/pages/FoodDetail.tsx
  client/src/pages/Main.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Search.tsx
  client/src/pages/Welcome.tsx
  client/src/pages/WishList.tsx
  client/src/store/ComparisonSlice.ts
  client/src/store/SearchInfoSlice.ts
  client/tailwind.config.js
Labels: 🐞 Bug Fix, 📱 Client, 🔨Refactoring, 🖥️ Server, ⏳ TODO

#214 fix: 서버 배포 시 application.yml 파일을 인식하지 못하는 에러 해결
  application.yml
  backend/.gitignore
  backend/caches/8.1.1/gc.properties
  backend/caches/transforms-3/gc.properties
  backend/daemon/8.1.1/registry.bin
  backend/daemon/8.1.1/registry.bin.lock
  backend/src/main/java/food/backend/oauth/common/filter/AuthenticationFilter.java
  backend/src/main/java/food/backend/oauth/common/jwt/JwtProviderImpl.java
Labels: 🐞 Bug Fix, 🌎 Deploy, 🖥️ Server, ⏳ TODO

#215 refactor: spring batch에서 사용되는 민감 정보 환경변수 설정
  backend/src/main/java/food/backend/batch/config/WebClientConfig.java
  backend/src/main/java/food/backend/batch/service/FoodDataApiService.java
Labels: 🌎 Deploy, 🔨Refactoring, 🖥️ Server, ⏳ TODO

#217 fix: SQL 문법 오류로 인한 배치 프로세스 작동 에러 해결
  backend/src/main/java/food/backend/batch/service/StoreFoodDataService.java
Labels: 🐞 Bug Fix, 🖥️ Server, ⏳ TODO

#218 design: 메인화면 등 CSS 수정
  .github/workflows/client-deploy-action.yml
  client/src/components/AgreementUtilization.tsx
  client/src/components/ComparisonFood.tsx
  client/src/components/Food.tsx
  client/src/components/Footer.tsx
  client/src/components/FooterMain.tsx
  client/src/components/KeywordComponent.tsx
  client/src/components/PrivacyPolicy.tsx
  client/src/components/SearchMiniOptionComp.tsx
  client/src/components/SearchOption.tsx
  client/src/components/SearchOptionBar.tsx
  client/src/components/modal/ComparisonModal.tsx
  client/src/components/modal/ComparisonViewModal.tsx
  client/src/pages/CustomerSupport.tsx
  client/src/pages/FoodDetail.tsx
  client/src/pages/Main.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Search.tsx
  client/src/store/ComparisonSlice.ts
  client/src/store/SearchInfoSlice.ts
Labels: 🐞 Bug Fix, 📱 Client, 🔨Refactoring, ⏳ TODO
